name: Laravel CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ جلب الكود من GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ إعداد PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # أو الإصدار اللي تستخدمينه
        extensions: mbstring, bcmath, sqlite

    # 3️⃣ تثبيت Composer dependencies
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # 4️⃣ إعداد Laravel environment
    - name: Setup Laravel Environment
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache

    # 5️⃣ تشغيل الاختبارات
    - name: Run Tests
      run: php artisan test --no-interaction --verbose

    # 6️⃣ Build (لو عندك Frontend)
    - name: Install Node.js & Build Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: |
        npm install
        npm run build

    # 7️⃣ نشر التقارير أو Monitoring
    - name: Upload Test Logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: laravel-test-logs
        path: storage/logs/*.log
